### ISSUE TITLE
JSBI values are compared incorrectly

### ISSUE THREAD

**Issue by h0tw4t3r** [Uniswap/v3-sdk#115]
Hello.
https://github.com/Uniswap/v3-sdk/blob/545fb4eb9003cd20c185fdd62949008695283012/src/entities/pool.ts#L290
Here two JSBI numbers are compared with type coercing, I think they should be compared just as few lines above with help of `JSBI.notEqual`.

**Comment by marktoda** [comment]
Great catch, thanks for reporting this!

**Comment by marktoda** [comment]
Fixed here https://github.com/Uniswap/v3-sdk/pull/130
