### ISSUE TITLE
create pool and Mint new Position

### ISSUE THREAD

**Issue by ramdanhere** [Uniswap/v3-sdk#127]
Hi there, I want to ask about creating new pool and providing new liquidity.

On the first step, I have successfully create and initialize the new pool pair via contract NonfungiblePositionManager -> createAndInitializePoolIfNecessary(args...)

but when I try to mint new position using contract NonfungiblePositionManager -> mint(args...), I got my transaction reverted without any error message. I am sure that I have pass the right function paramater, and I have approve both token to the NonfungiblePositionManager address.

I got the issue above using golang.

And when I try using typescript with uniswap sdk I got this error:
```
/home/money/sdk/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^

Error: Invariant failed: ZERO_LIQUIDITY
```

**Comment by Wizenseeker23** [comment]
yeah i dont use that uniswap thats the only wallet i never use it is either
etherscan or polygonscan polygon wallet it either what i use when i am not
using opensea.io when it comes to my nfts trading cards with
blitzonairdogsnfts with opensea.io when i have an account with opensea.io
when i first started out with in doing blitzondognfts making my assets
value in networth revenu and using real money in the app to get it too
where i am at today or meta mask or solaon wallet polygon is the best one
for any nfts

Robert Tompkins & Brittanya ocampo  Tompkins
