### ISSUE TITLE
is there any function in v3 like getReserves() of v2?

### ISSUE THREAD

**Issue by hebeillc** [Uniswap/v3-sdk#42]
I want to get the balance of token in v3，is there any function in v3 like getReserves() of v2?
thanks

**Comment by h0tw4t3r** [comment]
UniswapV3 has a tick-indexed state, and it doesn't store amount of tokens locked in reserves, but instead tracks liquidity and sqrtPrice, from which amount of tokens held can be calculated

**Comment by muhammadsamir11** [comment]
> UniswapV3 has a tick-indexed state, and it doesn't store amount of tokens locked in reserves, but instead tracks liquidity and sqrtPrice, from which amount of tokens held can be calculated

Do you have the formula for that in javascript
